CVGS/Areas/Admin/Controllers/EventController.cs
using CVGS.Data;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CVGS.Areas.Admin.Controllers
{
    public class EventController : Controller
    {
        const string ADMIN_ROLE = "Employee";

        // GET: Admin/Event
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public ActionResult Index()
        {
            CVGSAppEntities db = new CVGSAppEntities();
            return View(db.Events.OrderBy(e => e.StartTime));
        }

        // GET: Admin/Event/Create
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Event/Create
        [HttpPost]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Create(Event newEvent)
        {
            var db = new CVGSAppEntities();

            // Event name unique
            if (db.Events.Any(e => e.Title == newEvent.Title))
            {
               ModelState.AddModelError("Title", "An event with this name already exists.");
            }

            ValidateEvent(newEvent);

            if (!ModelState.IsValid)
            {
                return View(newEvent);
            }

            try
            {
                newEvent.Id = Guid.NewGuid().ToString();
                db.Events.Add(newEvent);
                await db.SaveChangesAsync();
                TempData["message"] = $"Record for '{newEvent.Title}' successfully added";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error: {ex.GetBaseException().Message}");
                return View(newEvent);
            }
        }

        // GET: Admin/Event/Edit/{id}
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction(nameof(Index));
            }

            CVGSAppEntities db = new CVGSAppEntities();
            var model = await db.Events.FindAsync(id);
            if (model == null)
            {
                TempData["message"] = string.Format("Event record with {0} id was not found", id);
                RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // POST: Admin/Event/Edit/{id}
        [HttpPost]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Edit(Event updatedEvent)
        {
            CVGSAppEntities db = new CVGSAppEntities();

            if (updatedEvent == null || string.IsNullOrEmpty(updatedEvent.Id))
            {
                return RedirectToAction(nameof(Index));
            }

            // Unqiue Name
            if(db.Events.Any(e => e.Title == updatedEvent.Title && e.Id != updatedEvent.Id))
            {
                ModelState.AddModelError("Title", "An event with this name already exists.");
            }

            try
            {
                var existingEvent = await db.Events.FindAsync(updatedEvent.Id);
                if (existingEvent == null)
                {
                    TempData["message"] = string.Format("Event record with {0} id was not found", updatedEvent.Id);
                    RedirectToAction(nameof(Index));
                }

                ValidateEvent(updatedEvent);

                if (!ModelState.IsValid)
                {
                    return View(updatedEvent);
                }

                existingEvent.Title = updatedEvent.Title;
                existingEvent.Description = updatedEvent.Description;
                existingEvent.StartTime = updatedEvent.StartTime;
                existingEvent.EndTime = updatedEvent.EndTime;
                existingEvent.MaxAttendeeNumber = updatedEvent.MaxAttendeeNumber;
                existingEvent.IsIRL = updatedEvent.IsIRL;
                existingEvent.Location = updatedEvent.Location;

                await db.SaveChangesAsync();
                TempData["message"] = $"Record for '{updatedEvent.Title}' successfully updated";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(updatedEvent);
            }
        }

        // GET: Admin/Event/Delete/{id}
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction(nameof(Index));
            }

            CVGSAppEntities db = new CVGSAppEntities();
            var model = await db.Events.FindAsync(id);
            if (model == null)
            {
                TempData["message"] = string.Format("Event record with {0} id was not found", id);
                RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // POST: Admin/Event/Delete/{id}
        [HttpPost]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Delete(Event model)
        {
            CVGSAppEntities db = new CVGSAppEntities();
            try
            {
                db.Events.Attach(model);
                db.Events.Remove(model);
                await db.SaveChangesAsync();
                TempData["message"] = $"Record successfully deleted";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error: {ex.GetBaseException().Message}");
                return View(model);
            }
        }

        private void ValidateEvent(Event model)
        {
            // Start date must be in future
            if (model.StartTime < DateTime.Now)
            {
                ModelState.AddModelError("StartTime", "Event start time must be in future.");
            }

            // End date must be in future
            if (model.EndTime < DateTime.Now)
            {
                ModelState.AddModelError("EndTime", "Event end time must be in future.");
            }

            // End date must be after start time.
            if (model.EndTime < model.StartTime)
            {
                ModelState.AddModelError("EndTime", "Event can not end before start time.");
            }
        }
    }
}

CVGS/Areas/Admin/Controllers/GameController.cs
using System;
using CVGS.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CVGS.Areas.Admin.Controllers
{

    public class GameController : Controller
    {
        const string ADMIN_ROLE = "Employee";

        // GET: Admin/Game
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public ActionResult Index()
        {
            CVGSAppEntities db = new CVGSAppEntities();
            var games = db.Games;
            var categories = db.GameCategories.ToDictionary(item => item.Id, item => item.Name);
            var platforms = db.GamePlatforms.ToDictionary(item => item.Id, item => item.Name);
            foreach (var game in games)
            {
                game.CategoryName = game.CategoryId == null ? "None" : categories[(int)game.CategoryId];
                game.PlatformName = game.PlatformId == null ? "None" : platforms[(int)game.PlatformId];
            }
            return View(games.ToList());
        }

        // GET: Admin/Game/Create
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public ActionResult Create()
        {
            using (CVGSAppEntities db = new CVGSAppEntities())
            {
                var gameCategories = new SelectList(db.GameCategories.ToList(), "Id", "Name");
                ViewData["GameCategories"] = gameCategories;
                var gamePlatforms = new SelectList(db.GamePlatforms.ToList(), "Id", "Name");
                ViewData["GamePlatforms"] = gamePlatforms;
            }
            return View();
        }

        // POST: Admin/Game/Create
        [HttpPost]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Create(Game model)
        {
            model.Rating = 0;
            CVGSAppEntities db = new CVGSAppEntities();
            try
            {
                //Game name unique
                if (db.Games.Any(g => g.Title == model.Title))
                {
                    ModelState.AddModelError("Title", "A game with this name already exists.");
                }

                // Release Year is integer between 1985 and 2020
                if (model.ReleaseYear != null)
                {
                    if (model.ReleaseYear != (int)model.ReleaseYear)
                    {
                        ModelState.AddModelError("ReleaseYear", "The release year must be an integer.");
                    }
                    else if ((int)model.ReleaseYear < 1985 || (int)model.ReleaseYear > 2020)
                    {
                        ModelState.AddModelError("ReleaseYear", "The release year must be between 1985 and 2020.");
                    }
                }
                if (!ModelState.IsValid)
                {
                    var gameCategories = new SelectList(db.GameCategories.ToList(), "Id", "Name");
                    ViewData["GameCategories"] = gameCategories;
                    var gamePlatforms = new SelectList(db.GamePlatforms.ToList(), "Id", "Name");
                    ViewData["GamePlatforms"] = gamePlatforms;
                    return View(model);
                }
                model.Id = Guid.NewGuid().ToString();
                db.Games.Add(model);
                await db.SaveChangesAsync();
                TempData["message"] = $"Record for '{model.Title}' successfully added";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error: {ex.GetBaseException().Message}");
                var gameCategories = new SelectList(db.GameCategories.ToList(), "Id", "Name");
                ViewData["GameCategories"] = gameCategories;
                var gamePlatforms = new SelectList(db.GamePlatforms.ToList(), "Id", "Name");
                ViewData["GamePlatforms"] = gamePlatforms;
                return View(model);
            }
        }

        // GET: Admin/Game/Edit/{id}
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Edit(string Id)
        {
            if (string.IsNullOrEmpty(Id))
            {
                return RedirectToAction(nameof(Index));
            }
            CVGSAppEntities db = new CVGSAppEntities();
            try
            {
                var model = await db.Games.FindAsync(Id);
                if (model == null)
                {
                    TempData["message"] = string.Format("Game record with {0} id was not found", Id);
                    RedirectToAction(nameof(Index));
                }
                var gameCategories = new SelectList(db.GameCategories.ToList(), "Id", "Name");
                ViewData["GameCategories"] = gameCategories;
                var gamePlatforms = new SelectList(db.GamePlatforms.ToList(), "Id", "Name");
                ViewData["GamePlatforms"] = gamePlatforms;
                return View(model);
            }
            catch
            {
                TempData["message"] = string.Format("Unexpected error occurred while updating a game (id = {0})", Id);
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Admin/Game/Edit/{id}
        [HttpPost]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Edit(Game model)
        {
            if (string.IsNullOrEmpty(model.Id))
            {
                return RedirectToAction(nameof(Index));
            }
            CVGSAppEntities db = new CVGSAppEntities();
            try
            {
                // Unique Name
                if (db.Games.Any(e => e.Title == model.Title && e.Id != model.Id))
                {
                    ModelState.AddModelError("Title", "An event with this name already exists.");
                }
                // Release Year is integer between 1985 and 2020
                if (model.ReleaseYear != null)
                {
                    if (model.ReleaseYear != (int)model.ReleaseYear)
                    {
                        ModelState.AddModelError("ReleaseYear", "The release year must be an integer.");
                    }
                    else if ((int)model.ReleaseYear < 1985 || (int)model.ReleaseYear > 2020)
                    {
                        ModelState.AddModelError("ReleaseYear", "The release year must be between 1985 and 2020.");
                    }
                }
                if (!ModelState.IsValid)
                {
                    var gameCategories = new SelectList(db.GameCategories.ToList(), "Id", "Name");
                    ViewData["GameCategories"] = gameCategories;
                    var gamePlatforms = new SelectList(db.GamePlatforms.ToList(), "Id", "Name");
                    ViewData["GamePlatforms"] = gamePlatforms;
                    return View(model);
                }

                var game = await db.Games.FindAsync(model.Id);
                if (game == null)
                {
                    TempData["message"] = string.Format("Game record with {0} id was not found", model.Id);
                    RedirectToAction(nameof(Index));
                }
                game.Title = model.Title;
                game.Description = model.Description;
                game.ReleaseYear = model.ReleaseYear;
                game.CategoryId = model.CategoryId;
                game.PlatformId = model.PlatformId;
                game.Price = model.Price;
                game.ImageUrl = model.ImageUrl;
                await db.SaveChangesAsync();
                TempData["message"] = $"Record for '{model.Title}' successfully updated";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error: {ex.GetBaseException().Message}");
                var gameCategories = new SelectList(db.GameCategories.ToList(), "Id", "Name");
                ViewData["GameCategories"] = gameCategories;
                var gamePlatforms = new SelectList(db.GamePlatforms.ToList(), "Id", "Name");
                ViewData["GamePlatforms"] = gamePlatforms;
                return View(model);
            }
        }

        // GET: Admin/Game/Delete/{id}
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Delete(string Id)
        {
            if (string.IsNullOrEmpty(Id))
            {
                return RedirectToAction(nameof(Index));
            }

            CVGSAppEntities db = new CVGSAppEntities();
            var model = await db.Games.FindAsync(Id);
            if (model == null)
            {
                TempData["message"] = string.Format("Game record with {0} id was not found", Id);
                RedirectToAction(nameof(Index));
            }

            var categories = db.GameCategories.ToDictionary(item => item.Id, item => item.Name);
            var platforms = db.GamePlatforms.ToDictionary(item => item.Id, item => item.Name);

            model.CategoryName = model.CategoryId == null ? "None" : categories[(int)model.CategoryId];
            model.PlatformName = model.PlatformId == null ? "None" : platforms[(int)model.PlatformId];

            return View(model);
        }

        // POST: Admin/Game/Delete/{id}
        [HttpPost]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> Delete(Game model)
        {
            CVGSAppEntities db = new CVGSAppEntities();
            if (string.IsNullOrEmpty(model.Id))
            {
                return RedirectToAction(nameof(Index));
            }

            var game = await db.Games.FindAsync(model.Id);
            if (game == null)
            {
                TempData["message"] = string.Format("Game record with {0} id was not found", model.Id);
                RedirectToAction(nameof(Index));
            }
            try
            {

CVGS/Views/Shared/AuthorizationFailed.cshtml
@{
    ViewBag.Title = "Authorization Failed";
}

<h2>Authorization Failed</h2>
<p>@ViewData["Message"]</p>

CVGS/Views/Shared/_GameListPartial.cshtml
@model IEnumerable<CVGS.Data.Game>
@{
    ViewBag.Title = "Game List";
}

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {

            @Html.Partial("_GameTilePartial", item)
        }
    </div>
</div>

CVGS/Views/Shared/_GameTilePartial.cshtml
@model CVGS.Data.Game

<style>
    .game-tile {
        color: white;
        border: 1px solid lightskyblue;
        border-radius: 0.25rem;
        padding: 0;
        margin-bottom: 3rem;
    }

    .game-tile-footer {
        background-image: url(https://store.steampowered.com/public/images/v6/home/background_spotlight.jpg);
        padding: 1rem;
    }

    .game-image {
        width: 100%;
        max-height: 300px;
        min-height: 300px;
    }
</style>

<a href="/Home/ViewGame/@(Model.Id)">
    <div class="col-md-4">
        <div class="game-tile" title="Click to view game details">

            <img src="@(Model.ImageUrl)" alt="Game Cover of @Model.Title" class="game-image" />

            <div class="game-tile-footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col pull-left">
                            @Html.DisplayFor(item => item.Title)
                            (@Html.DisplayFor(item => item.PlatformName))
                        </div>
                        <div class="col pull-right">
                            @Html.DisplayFor(item => item.Price)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</a>

CVGS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link runat="server" rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="~/favicon.ico" type="image/ico" />
    <title>@ViewBag.Title - CVGS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CVGS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { Area = "" }, null)</li>
                    <li>@Html.ActionLink("Events", "Index", "Events", new { Area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { Area = "" }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { Area = "" }, null)</li>
                    @if (User.IsInRole("Employee"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Administration <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Manage Games", "Index", "Game", new { Area = "Admin" }, null)</li>
                                <li>@Html.ActionLink("Manage Events", "Index", "Event", new { Area = "Admin" }, null)</li>
                                <li>@Html.ActionLink("Manage Reviews", "Index", "Review", new { Area = "Admin" }, null)</li>
                                <li>@Html.ActionLink("Generate Reports", "Index", "Report", new { Area = "Admin" }, null)</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="color:#fff;">
            <p>&copy; @DateTime.Now.Year - CVGS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>