CVGS/Areas/Admin/Controllers/ReviewController.cs
using CVGS.Areas.Admin.Models;
using CVGS.Data;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using System.Web;

namespace CVGS.Areas.Admin.Controllers
{
    public class ReviewController : Controller
    {
        private readonly CVGSAppEntities db;

        public ReviewController()
        {
            if (db == null)
            {
                db = new CVGSAppEntities();
            }
        }

        const string ADMIN_ROLE = "Employee";
        // GET: Admin/Review
        [HttpGet]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public ActionResult Index()
        {
            var reviews = db.GameReviews.Where(r => !r.Approved);
            var model = new List<GameReviewApprovalModel>();
            var applicationUserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            foreach (var review in reviews)
            {
                var gameTitle = db.Games.FirstOrDefault(g => g.Id == review.GameId).Title;
                var reviewer = applicationUserManager.FindById(review.CreatedBy).UserName;
                model.Add(review.GameReviewToGameReviewApprovalModel(reviewer, gameTitle));
            }
            return View(model);
        }

       //[HttpPost]
        [CustomAuthorize(Roles = ADMIN_ROLE)]
        public async Task<ActionResult> ApproveReview(string id, bool approved)
        {
            if (!string.IsNullOrEmpty(id))
            {
                try
                {
                    var model = await db.GameReviews.FindAsync(id);
                    if (model == null)
                    {
                        TempData["message"] = string.Format("Review with {0} id was not found", id);
                    }
                    else
                    {
                        if (approved)
                        {
                            model.Approved = true;
                            await db.SaveChangesAsync();
                        }
                        else
                        {
                            db.GameReviews.Remove(model);
                            await db.SaveChangesAsync();
                        }
                    }
                    RedirectToAction(nameof(Index));
                }
                catch
                {

                }
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CVGS/Areas/Admin/Views/Review/Index.cshtml
@model IEnumerable<CVGS.Areas.Admin.Models.GameReviewApprovalModel>
@{
    ViewBag.Title = "Unapproved Reviews";
}

<style>
    .btn-bottom-margin {
        margin-bottom: 0.3em;
    }
</style>

<h2>Unapproved Reviews List</h2>

@if (Model != null && Model.Count() > 0)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.GameName)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedOn)</th>
                <th>@Html.DisplayNameFor(model => model.ReviewText)</th>
                <th></th>
            </tr>
        </thead>
        <tbody class="tbody">
            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.GameName)</td>
                <td>@Html.DisplayFor(modelItem => item.CreatedBy)</td>
                <td>@Html.DisplayFor(modelItem => item.CreatedOn)</td>
                <td>@Html.DisplayFor(modelItem => item.ReviewText)</td>
                <td>
                    <a href="@Url.Action("ApproveReview", "Review", new { id = item.Id, approved = true })" class="btn btn-success btn-sm btn-bottom-margin">Approve</a>&nbsp;&nbsp;
                    <a href="@Url.Action("ApproveReview", "Review", new { id = item.Id, approved = false })" class="btn btn-danger btn-sm">Decline</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No unapproved reviews.</p>
}