CVGS/Models/OrderViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CVGS.Models
{
    public class OrdersViewModel
    {
        public string Id { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMMM dd, yyyy, h:mm tt}")]
        [Display(Name = "Order Placed")]
        public DateTime OrderPlaced { get; set; }

        [Display(Name = "Items")]
        public int ItemNumber { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Total")]
        public decimal Total { get; set; }

        public List<GameThumbView> Games { get; set; }
    }

    public class GameThumbView
    {
        public string Id { get; set; }
        public string ImageUrl { get; set; }
    }
}

CVGS/Controllers/ProfileController.cs
using CVGS.Data;
using CVGS.Enums;
using CVGS.Models;
using CVGS.Models.ModelExtensions;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CVGS.Controllers
{
    public class ProfileController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            CVGSAppEntities db = new CVGSAppEntities();
            var applicationUserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            ProfileViewModel model;

            // determine if the profile owner is friend of the current user
            bool isInFriendList = false;
            bool isFriendedUser = false;
            if ((System.Web.HttpContext.Current.User != null) && System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId();
                isFriendedUser = userId == id || db.FriendLists.Any(f => f.userId == id && f.friendId == userId);
                isInFriendList = db.FriendLists.Any(f => f.userId == userId && f.friendId == id);
            }

            try
            {
                var user = await db.MemberUsers.FindAsync(id);
                if (user != null)
                {
                    // Get user's preferences
                    var categoryPrefs = (GameCategoryOptions)user.CategoryOptions;
                    var platformPrefs = (FavoritePlatforms)user.PlatformOptions;

                    model = new ProfileViewModel
                    {
                        Id = id,
                        DisplayName = applicationUserManager.FindById(id).UserName,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        FavoriteCatefories = categoryPrefs.ToString(),
                        FavoritePlatforms = platformPrefs.ToString(),
                        IsInUserFriendList = isInFriendList,
                        UserInProfileFriendList = isFriendedUser,
                        //ActionChecked = categoryPrefs.HasFlag(GameCategoryOptions.Action),
                        //AdventureChecked = categoryPrefs.HasFlag(GameCategoryOptions.Adventure),
                        //RolePlayingChecked = categoryPrefs.HasFlag(GameCategoryOptions.RolePlaying),
                        //SimulationChecked = categoryPrefs.HasFlag(GameCategoryOptions.Simulation),
                        //StrategyChecked = categoryPrefs.HasFlag(GameCategoryOptions.Strategy),
                        //PuzzleChecked = categoryPrefs.HasFlag(GameCategoryOptions.Puzzle),
                        //PCChecked = platformPrefs.HasFlag(FavoritePlatforms.PC),
                        //PlayStationChecked = platformPrefs.HasFlag(FavoritePlatforms.PlayStation),
                        //XboxChecked = platformPrefs.HasFlag(FavoritePlatforms.Xbox),
                        //NintendoChecked = platformPrefs.HasFlag(FavoritePlatforms.Nintendo),
                        //MobileChecked = platformPrefs.HasFlag(FavoritePlatforms.Mobile)
                    };

                    if (isFriendedUser)
                    {
                        // Get wish list games
                        var wishListIds = db.WishLists.Where(u => u.userId == id).Select(i => i.gameId).ToList();
                        var wishListGames = db.Games.Where(g => wishListIds.Contains(g.Id)).ToList();

                        // Get owned games
                        var orderIds = db.Orders.Where(o => o.UserId == id).Select(o => o.Id).ToList();
                        var gameIds = db.OrderItems.Where(oi => orderIds.Contains(oi.OrderId)).Select(oi => oi.GameId).ToList();
                        var purchasedGames = db.Games.Where(g => gameIds.Contains(g.Id)).ToList();

                        model.WishList = wishListGames;
                        model.OwnedGames = purchasedGames;

                        // Attach category and platform to wish list and games list
                        var categories = db.GameCategories.ToDictionary(item => item.Id, item => item.Name);
                        var platforms = db.GamePlatforms.ToDictionary(item => item.Id, item => item.Name);
                        foreach (var game in model.WishList)
                        {
                            if (categories.Any())
                            {
                                game.CategoryName = game.CategoryId == null ? "None" : categories[(int)game.CategoryId];
                            }
                            if (platforms.Any())
                            {
                                game.PlatformName = game.PlatformId == null ? "None" : platforms[(int)game.PlatformId];
                            }
                        }
                        foreach (var game in model.OwnedGames)
                        {
                            if (categories.Any())
                            {
                                game.CategoryName = game.CategoryId == null ? "None" : categories[(int)game.CategoryId];
                            }
                            if (platforms.Any())
                            {
                                game.PlatformName = game.PlatformId == null ? "None" : platforms[(int)game.PlatformId];
                            }
                        }
                    }
                }
                else
                {
                    return RedirectToAction("FriendList", "Manage");
                }
            }
            catch (Exception)
            {
                TempData["message"] = "Unexpected error occurred while retrieving user profile.";
                return RedirectToAction("FriendList", "Manage");
            }

            return View(model);
        }

        public ActionResult AddToFriendList(string id)
        {
            CVGSAppEntities db = new CVGSAppEntities();
            var userId = User.Identity.GetUserId();

            if (db.FriendLists.FirstOrDefault(f => f.userId == userId && f.friendId == id) == null)
            {
                db.FriendLists.Add(new FriendList { userId = userId, friendId = id });
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = id });
        }

        public ActionResult Unfriend(string id)
        {
            CVGSAppEntities db = new CVGSAppEntities();
            var userId = User.Identity.GetUserId();

            var friend = db.FriendLists.FirstOrDefault(f => f.userId == userId && f.friendId == id);
            if (friend != null)
            {
                db.FriendLists.Remove(friend);
                db.SaveChanges();
            }
            return RedirectToAction("FriendList", "Manage");
        }
    }
}

CVGS/Controllers/WishListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using CVGS.Data;
using Microsoft.AspNet.Identity;

namespace CVGS.Controllers
{
    public class WishListsController : Controller
    {
        private CVGSAppEntities db = new CVGSAppEntities();

        public ActionResult Index()
        {
            CVGSAppEntities db = new CVGSAppEntities();
            var userId = User.Identity.GetUserId();
            List<string> gameIds = db.WishLists.Where(w => w.userId == userId).Select(w => w.gameId).ToList();

            var games = db.Games.Where(g => gameIds.Contains(g.Id));
            var categories = db.GameCategories.ToDictionary(item => item.Id, item => item.Name);
            var platforms = db.GamePlatforms.ToDictionary(item => item.Id, item => item.Name);

            foreach (var game in games)
            {
                if (categories.Any())
                {
                    game.CategoryName = game.CategoryId == null ? "None" : categories[(int)game.CategoryId];
                }
                if (platforms.Any())
                {
                    game.PlatformName = game.PlatformId == null ? "None" : platforms[(int)game.PlatformId];
                }
            }

            return View(games);
        }

        public async Task<ActionResult> Add(string id)
        {
            var userId = User.Identity.GetUserId();

            if (db.WishLists.Any(c => c.userId == userId && c.gameId == id))
            {
                TempData["message"] = "This game is already in your wish list.";
                return RedirectToAction("ViewGame", new RouteValueDictionary(new { controller = "Home", action = "ViewGame", Id = id }));
            }

            var newWish = new WishList() { userId = userId, gameId = id };
            db.WishLists.Add(newWish);
            await db.SaveChangesAsync();
            return RedirectToAction("ViewGame", new RouteValueDictionary(new { controller = "Home", action = "ViewGame", Id = id }));
        }

        public async Task<ActionResult> Remove(string id)
        {
            var userId = User.Identity.GetUserId();

            if (!db.WishLists.Any(c => c.userId == userId && c.gameId == id))
            {
                TempData["message"] = "This game is not in your wish list.";
                return RedirectToAction("ViewGame", new RouteValueDictionary(new { controller = "Home", action = "ViewGame", Id = id }));
            }

            WishList wish = db.WishLists.FirstOrDefault(c => c.userId == userId && c.gameId == id);
            db.WishLists.Remove(wish);
            await db.SaveChangesAsync();
            return RedirectToAction("ViewGame", new RouteValueDictionary(new { controller = "Home", action = "ViewGame", Id = id }));
        }
    }
}

CVGS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CVGS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CVGS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style type="text/css">
    body {
        background: center top no-repeat #1b2838;
        color: white;
    }

    h2 {
        padding: 1em 0;
    }
    .vertical-space {
        margin-top: 3em;
    }

    .ui-autocomplete {
        position: absolute;
        top: 100%;
        left: 0;
        z-index: 1000;
        display: none;
        float: left;
        min-width: 160px;
        padding: 5px 0;
        margin: 2px 0 0;
        list-style: none;
        font-size: 14px;
        text-align: left;
        background-color: #ffffff;
        border: 1px solid #cccccc;
        border: 1px solid rgba(0, 0, 0, 0.15);
        border-radius: 4px;
        -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
        background-clip: padding-box;
    }

        .ui-autocomplete > li > div {
            display: block;
            padding: 3px 20px;
            clear: both;
            font-weight: normal;
            line-height: 1.42857143;
            color: #333333;
            white-space: nowrap;
        }

    .ui-state-hover,
    .ui-state-active,
    .ui-state-focus {
        text-decoration: none;
        color: #262626;
        background-color: #dcdcdc;
        cursor: pointer;
    }

    .ui-helper-hidden-accessible {
        border: 0;
        clip: rect(0 0 0 0);
        height: 1px;
        margin: -1px;
        overflow: hidden;
        padding: 0;
        position: absolute;
        width: 1px;
    }

</style>


<br />
<br />
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/Content/Images/apex.jpg" alt="Apex" class="img-responsive" />
        </div>
        <div class="item">
            <img src="~/Content/Images/callofduty.png" alt="CallOfDuty" class="img-responsive" />
        </div>
        <div class="item">
            <img src="~/Content/Images/fallout.png" alt="Fallout" class="img-responsive" />
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
@*<h3>Search Game(s)</h3>*@
<div class="container vertical-space">

    @using (Html.BeginForm("SearchGames", "Home", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="col-md-8 col-md-offset-2">
            <div class="input-group">
                <input type="text" name="search" id="search" placeholder="Search games by title" class="form-control col-md-6">
                <span class="input-group-btn">
                    <input type="submit" value="Search" class="btn btn-primary" data-disable-with="Search">
                </span>
            </div>
        </div>
        <br/>
        <br/>
        <h2 style="color:white;">Featured and Recommended</h2>
        @Html.Partial("_GameListPartial")
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        //$(document).ready(function () {
        //    // if the search query string is not empty, remove it from URL
        //    if (window.location.search != "") {
        //        clearCurrentURL();
        //    }
        //});

        //function clearCurrentURL() {
        //    var urlWithoutParams = location.protocol + "//" + location.host + location.pathname;
        //    window.history.replaceState({}, document.title, urlWithoutParams);
        //}

        $(document).ready(function () {
            $("#search").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Home/AutoComplete",
                        type: "POST",
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.label, value: item.label };
                            }));
                        }
                    })
                },
                messages: {
                    noResults: "", results: ""
                },
                minLength: 2
            });
        });
    </script>
}

CVGS/Views/Home/Library.cshtml
@model IEnumerable<CVGS.Data.Game>
@{
    ViewBag.Title = "My Games Library";
}

<h2>@ViewBag.Title</h2>

<br />

@{
    if (Model.Any())
    {
        @Html.Partial("_GameListPartial")
    } else
    {
        <p>You currently do not own any games.</p>
    }
}

CVGS/Views/Home/ViewGame.cshtml
@model CVGS.Models.GameViewModel

@{
    ViewBag.Title = Model.Title;
    var rating = Model.Rating == null ? 0 : Model.Rating;
    decimal ratingPercent = 0;
    if (rating != null)
    {
        ratingPercent = (decimal)(rating / 5) * 100;
    }
}

<style type="text/css">
    body {
        background: center top no-repeat #1b2838;
        color: whitesmoke;
    }

    textarea {
        max-width: 450px;
    }

    body .modal {
        color: #001a66;
    }

    .img-responsive {
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
    }

    .progress-bar {
        color: black;
    }

    .vertical-align {
        display: flex;
        align-items: center;
    }

    .modal-content {
        position: relative;
        display: flex;
        flex-direction: column;
        margin-top: 50%;
    }

    .small-text {
        font-size: x-small;
    }

    table, td {
        border-bottom: 1px solid #808080;
    }

    .btn-margin-top {
        margin-top: 10px;
    }

    .margin-bottom {
        margin-bottom: 3em;
    }

    .hr-reviews {
        border-top: 1px solid gray;
        width: 80%;
    }

    .unapproved-review {
        color: gray;
        font-style: italic;
    }

    .pending-approval-notice {
        margin-top: 3em;
        font-weight: bold;
        color: orange;
    }

    .game-image {
        width: 100%;
        max-height: 300px;
        min-height: 300px;
    }

    /* Rating Star Widgets Style */
    .text-center {
        text-align: center;
    }

    .rating-stars ul {
        list-style-type: none;
        padding: 0;
        -moz-user-select: none;
        -webkit-user-select: none;
    }

    .rating-stars ul > li.star {
        display: inline-block;
    }

        /* Idle State of the stars */
        .rating-stars ul > li.star > i.fa {
            font-size: 2.5em; /* Change the size of the stars */
            color: #ccc; /* Color on idle state */
        }

        /* Hover state of the stars */
        .rating-stars ul > li.star.hover > i.fa {
            color: #FFCC36;
        }

        /* Selected state of the stars */
        .rating-stars ul > li.star.selected > i.fa {
            color: #FF912C;
        }
</style>

<hr />
<div class="row vertical-align">
    <div class="col-sm-4">
        <img src="@Model.ImageUrl" alt="Game Cover of @Model.Title" class="img-responsive img-rounded" />
    </div>
    <div class="col-sm-8" style="padding-left:5%;">
        <h2 id="gameTitle">@Model.Title</h2>
        <div class="container">
            <div class="row vertical-align">
                <div class="col-sm-3">
                    <h4>@Model.ReleaseYear</h4>
                </div>
                <div class="col-sm-2">
                    @if (rating != 0)
                    {
                        <p style="text-align:center;">Rated @Model.Rating out of 5</p>
                        <div class="progress">
                            @if (rating >= 4)
                            {
                                <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="@ratingPercent"
                                     aria-valuemin="0" aria-valuemax="100" style="width:@ratingPercent%">
                                </div>
                            }
                            else if (rating < 4 && rating >= 3)
                            {
                                <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="@ratingPercent"
                                     aria-valuemin="0" aria-valuemax="100" style="width:@ratingPercent%">
                                </div>
                            }
                            else if (rating < 3 && rating >= 2)
                            {
                                <div class="progress-bar progress-bar-warning progress-bar-striped" role="progressbar" aria-valuenow="@ratingPercent"
                                     aria-valuemin="0" aria-valuemax="100" style="width:@ratingPercent%">
                                </div>
                            }
                            else if (rating < 2 && rating >= 1)
                            {
                                <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="@ratingPercent"
                                     aria-valuemin="0" aria-valuemax="100" style="width:@ratingPercent%">
                                </div>
                            }
                        </div>
                    }
                    else
                    {
                        <div>Not Yet Rated</div>
                    }
                </div>
                <div class="col-sm-2">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#ratingModal">Rate Game</button>
                    }
                </div>
            </div>
        </div>
        <hr style="clear:both;" />
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.CategoryId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CategoryName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PlatformId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PlatformName)
            </dd>
        </dl>
        @{
            if (Model.IsPurchased)
            {
                <p>You Own This Game</p>
            }
            else
            {
                <h3>$@Model.Price</h3>
            }
        }

        <br />
        @if (User.Identity.IsAuthenticated)
        {
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4">
                        @if (Model.IsPurchased)
                        {
                            <button class="btn btn-primary btn-lg" data-toggle="modal" onclick="downloadGame();">Download</button>
                        }
                        else if (!Model.IsInUserCart)
                        {

                            @Html.ActionLink("Add to Cart", "Add", "Cart", new { id = Model.Id }, new { @class = "btn btn-success btn-lg" })

                        }
                        else
                        {
                            <p style="font-size:large">This game is in your shopping cart.</p>
                        }
                    </div>
                    <div class="col-md-4">
                        @if (!Model.IsPurchased)
                        {
                            if (Model.IsInWishList)
                            {
                                @Html.ActionLink("Remove from Wish List", "Remove", "WishLists", new { id = Model.Id }, new { @class = "btn btn-primary btn-lg" })
                            }
                            else
                            {
                                @Html.ActionLink("Add to Wish List", "Add", "WishLists", new { id = Model.Id }, new { @class = "btn btn-primary btn-lg" })
                            }
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<hr />
<div>
    <h4 style="text-align:center;">ABOUT THIS GAME</h4>
    <br />
    <p>
        @Html.DisplayFor(model => model.Description)
    </p>
</div>
<hr />

<div>
    <h4 style="text-align:center;">CUSTOMER REVIEWS</h4>
    @if (User.Identity.IsAuthenticated)
    {
        <button class="btn btn-primary margin-bottom" data-toggle="modal" data-target="#reviewModal">Add Review</button>
    }
    @Html.Partial("_ReviewListPartial", Model.Reviews)
</div>

@*RATING MODAL*@
<div class="modal fade" id="ratingModal" tabindex="-1" role="dialog" aria-labelledby="ratingModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title" id="ratingModalTitle">How do you rate this game?</h4>
            </div>
            <div class="modal-body">
                <form class="form-inline">
                    <label for="rating" class="modal-label">On a scale from 1 to 5:</label>
                    <div id="rating" class='rating-stars text-center'>
                        <ul id='stars'>
                            <li class='star' title='Poor' data-value='1'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='Fair' data-value='2'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='Good' data-value='3'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='Excellent' data-value='4'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='WOW!!!' data-value='5'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                        </ul>
                    </div>
                    @*<div class="form-group">
            <label for="ratingValue" class="modal-label">On a scale from 1 to 5:</label>
            <select name="rating" class="form-control" id="ratingValue" style="margin-left:15px;">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>*@
                    <input type="hidden" id="gameId" value="@Model.Id" />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnSaveRating" onclick="SaveRating();">Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>@Model.Title
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        var obj = @Html.Raw(Json.Encode(Model));

        $(document).ready(function () {
            /* 1. Visualizing things on Hover */
            $('#stars li').on('mouseover', function () {
                var onStar = parseInt($(this).data('value'), 10); // The star currently mouse on

                // Now highlight all the stars that's not after the current hovered star
                $(this).parent().children('li.star').each(function (e) {
                    if (e < onStar) {
                        $(this).addClass('hover');
                    }
                    else {
                        $(this).removeClass('hover');
                    }
                });

            }).on('mouseout', function () {
                $(this).parent().children('li.star').each(function (e) {
                    $(this).removeClass('hover');
                });
            });


            /* 2. Action to perform on click */
            $('#stars li').on('click', function () {
                var onStar = parseInt($(this).data('value'), 10); // The star currently selected
                var stars = $(this).parent().children('li.star');

                for (i = 0; i < stars.length; i++) {
                    $(stars[i]).removeClass('selected');
                }

                for (i = 0; i < onStar; i++) {
                    $(stars[i]).addClass('selected');
                }
            });
        });

        function downloadGame() {
            download(obj.Title + '.txt', obj.Title);
        }

        function download(filename, text) {
            var element = document.createElement('a');
            element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
            element.setAttribute('download', filename);

            element.style.display = 'none';
            document.body.appendChild(element);

            element.click();

            document.body.removeChild(element);
        }

        function SaveRating() {
            // determine which star was selected
            var rating = 0;
            var stars = $('#stars li').parent().children('li.star');

            for (i = stars.length - 1; i >= 0; i--) {
                if ($(stars[i]).hasClass('selected')) {
                    rating = i + 1;
                    break;
                }
            }

            // if no rating was selected, just close the modal
            if (rating === 0) {
                $('#ratingModal').modal('hide');
                return;
            }

            var ratingObj = {
                GameId: $('#gameId').val(),
                Rating: rating
            };

            $.ajax({
                url: "/Home/AddRating",
                data: JSON.stringify(ratingObj),
                type: "POST",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    //$('#ratingValue').val(result.Rating);
                    $('#ratingModal').modal('hide');
                    location.reload();
                },
                error: function (result) {
                    alert(result.Error);
                    $('#ratingModal').modal('hide');
                },
            });
        }
    </script>
}